CREATE TABLE [dbo].[Texts]
(
	TextID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	AccountID INT NOT NULL,
	RoomID INT NOT NULL,
	Content VARCHAR(100) NOT NULL,

	CONSTRAINT fk_Texts_AccountID FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID),
	CONSTRAINT fk_Texts_RoomID FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
)

